name: k8s image sync
on: push
jobs:
  k8s-image-sync:
    name: k8s image sync
    runs-on: ubuntu-latest
    steps:
    - name: sync
      uses: duqian42707/actions/k8s-image-sync@master
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: duqian42707
        kubernetes_version: v1.14.8
  github-package-k8s-image-sync:
    name: github package k8s image sync
    runs-on: ubuntu-latest
    steps:
    - name: sync
      uses: duqian42707/actions/k8s-image-sync@master
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.GITHUB_DOCKER_PASSWORD }}
        registry: docker.pkg.github.com
        repository: duqian42707/duqian42707
        kubernetes_version: v1.14.8
